version: '3'

services:
  backend:
    container_name: trpd_backend
    build:
      context: ../
      dockerfile: ./docker/backend/Dockerfile

  react:
    container_name: trpd_react
    build:
      context: ../
      dockerfile: ./docker/react/Dockerfile
    links:
      - backend

  nginx:
    container_name: trpd_nginx
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    links:
      - backend
      - react
    ports:
      - 3000:80